language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
env:
  global:
    - NODE_VERSION=8.9.3
    - NPM_VERSION=^6.3.0
    - BUILD_LEADER_ID=4
  matrix:
    - XDEBUG_VERSION=2.7.0
    - XDEBUG_VERSION=3.0.0

matrix:
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - git clone https://github.com/RobberPhex/xdebug.git /tmp/xdebug/ -b "$XDEBUG_VERSION"
  - pushd /tmp/xdebug/
  - phpize && ./configure && make -j $(nproc) && make install
  - popd
  - phpenv config-add travis-php.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION --depth 0

install:
  - npm ci

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - ./node_modules/.bin/nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)
